// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzgwkfkeoeyeusscaajk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6Z3drZmtlb2V5ZXVzc2NhYWprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjE0MDksImV4cCI6MjA3MzkzNzQwOX0.LCyjImL29Naw3nbvcTLwB1aFi7jj6A6nz5tsbLzv5r4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});